paragraph_dict = {"1": [
    "Sometimes", "I", "think", "about", "how", "strange", "it", "is", "that", "the", "sky", "can", "be", "so",
    "many", "different", "shades", "of", "blue", "depending", "on", "the", "time", "of", "day", "and", "how",
    "when", "the", "clouds", "drift", "across", "it", "feels", "like", "they", "are", "moving", "slowly", "even",
    "though", "they", "are", "racing", "with", "the", "wind", "and", "people", "often", "forget", "to", "look",
    "up", "because", "we", "spend", "so", "much", "time", "focused", "on", "screens", "or", "sidewalks", "or",
    "the", "things", "right", "in", "front", "of", "us", "and", "meanwhile", "the", "whole", "world", "above",
    "is", "shifting", "and", "stretching", "in", "ways", "we", "rarely", "stop", "to", "notice", "and", "then",
    "there", "are", "birds", "that", "ride", "those", "winds", "with", "effortless", "grace", "and", "somehow",
    "know", "when", "to", "migrate", "thousands", "of", "miles", "across", "continents", "without", "maps",
    "or", "GPS", "which", "makes", "me", "wonder", "about", "instincts", "and", "how", "much", "we", "rely",
    "on", "them", "versus", "logic", "and", "planning", "and", "speaking", "of", "planning", "it", "is",
    "funny", "how", "carefully", "we", "can", "schedule", "a", "day", "and", "then", "something", "completely",
    "random", "can", "throw", "it", "off", "like", "spilling", "coffee", "or", "missing", "a", "bus", "or",
    "just", "getting", "lost", "in", "a", "conversation", "that", "went", "longer", "than", "expected", "and",
    "maybe", "that", "is", "part", "of", "what", "keeps", "life", "interesting", "because", "predictability",
    "can", "be", "comforting", "but", "also", "boring", "if", "it", "stretches", "on", "too", "long", "so",
    "we", "balance", "between", "wanting", "stability", "and", "craving", "change", "and", "even", "in",
    "something", "as", "small", "as", "food", "we", "chase", "variety", "because", "as", "much", "as", "someone",
    "loves", "pizza", "or", "pasta", "there", "is", "always", "a", "moment", "when", "they", "want", "something",
    "spicy", "or", "sweet", "or", "completely", "different", "and", "it", "reminds", "me", "of", "how", "music",
    "works", "since", "you", "can", "listen", "to", "the", "same", "genre", "over", "and", "over", "and", "still",
    "suddenly", "crave", "a", "completely", "different", "sound", "maybe", "soft", "acoustic", "instead", "of",
    "heavy", "bass", "or", "jazz", "instead", "of", "pop", "and", "those", "switches", "keep", "us", "awake",
    "to", "new", "experiences", "the", "same", "way", "walking", "a", "slightly", "different", "route", "home",
    "can", "make", "you", "notice", "a", "tree", "you", "never", "really", "saw", "or", "a", "building", "that",
    "has", "been", "there", "all", "along", "but", "seemed", "invisible", "until", "you", "changed", "your",
    "perspective", "and", "sometimes", "I", "think", "memory", "works", "like", "that", "too", "where", "things",
    "are", "sitting", "in", "the", "background", "unnoticed", "until", "something", "small", "shines", "a",
    "light", "on", "them", "like", "a", "smell", "of", "rain", "on", "pavement", "or", "the", "sound", "of", "a",
    "certain", "song", "and", "suddenly", "an", "entire", "chapter", "of", "life", "comes", "flooding", "back",
    "with", "details", "you", "did", "not", "realize", "you", "still", "remembered", "and", "that", "is", "both",
    "comforting", "and", "overwhelming", "because", "it", "reminds", "you", "of", "how", "much", "is", "stored",
    "in", "the", "corners", "of", "your", "mind", "waiting", "quietly"
],
                  "2": [
    "I", "wander", "through", "a", "hallway", "of", "half", "remembered", "tunes",
    "a", "draft", "sneaks", "under", "the", "door", "and", "smells", "like", "rain",
    "the", "kettle", "waits", "with", "quiet", "patience",
    "someone", "upstairs", "drags", "a", "chair", "and", "the", "floor", "answers",
    "sunlight", "lands", "on", "a", "stack", "of", "books", "like", "a", "gentle", "spotlight",
    "dust", "performs", "an", "unhurried", "ballet", "in", "the", "beam",
    "a", "list", "on", "the", "fridge", "bends", "under", "a", "magnet", "shaped", "like", "a", "moon",
    "the", "clock", "pretends", "to", "be", "important", "and", "clicks", "its", "tiny", "metronome",
    "my", "shoes", "keep", "the", "outline", "of", "yesterdays", "walk",
    "a", "postcard", "insists", "that", "horizons", "are", "invitations",
    "the", "cat", "yawns", "with", "theatrical", "commitment",
    "a", "sock", "lives", "a", "secret", "life", "behind", "the", "couch",
    "street", "noise", "braids", "with", "birdsong", "in", "a", "curious", "harmony",
    "the", "plant", "on", "the", "sill", "negotiates", "with", "gravity", "and", "wins",
    "a", "forgotten", "lyric", "returns", "like", "a", "boomerang",
    "I", "test", "a", "pen", "on", "the", "margin", "and", "draw", "a", "hopeful", "spiral",
    "the", "mirror", "gives", "advice", "in", "the", "language", "of", "eyebrows",
    "a", "mug", "remembers", "every", "morning", "it", "has", "carried",
    "keys", "lie", "on", "the", "table", "like", "scattered", "punctuation",
    "the", "door", "hinge", "sings", "a", "stubborn", "anthem",
    "I", "consider", "toast", "as", "if", "it", "were", "a", "philosophy",
    "steam", "paints", "temporary", "clouds", "on", "the", "window",
    "a", "bicycle", "bell", "rings", "and", "the", "day", "nods", "back",
    "I", "fold", "a", "piece", "of", "paper", "into", "a", "tentative", "airplane",
    "the", "calendar", "flutters", "with", "future", "rumors",
    "an", "orange", "waits", "to", "become", "a", "small", "sun",
    "my", "inbox", "behaves", "like", "a", "tide", "that", "never", "rests",
    "I", "promise", "to", "answer", "later", "and", "hope", "later", "is", "kind",
    "a", "breeze", "edits", "the", "curtains", "with", "invisible", "scissors",
    "the", "floorboard", "near", "the", "desk", "keeps", "a", "diary", "of", "creaks",
    "I", "rehearse", "a", "joke", "meant", "for", "no", "one", "in", "particular",
    "the", "neighbors", "dog", "sends", "a", "short", "memo", "to", "the", "block",
    "a", "pencil", "sharpener", "chews", "its", "way", "to", "clarity",
    "socks", "argue", "about", "where", "the", "other", "went",
    "a", "hat", "on", "the", "hook", "dreams", "of", "weather",
    "the", "lamp", "wears", "a", "friendly", "halo",
    "soup", "on", "the", "stove", "whispers", "patient", "wisdom",
    "notes", "on", "a", "sticky", "square", "plot", "their", "escape",
    "a", "map", "folds", "itself", "into", "a", "quiet", "mountain",
    "the", "chair", "accepts", "the", "inevitable", "symphony", "of", "squeaks",
    "a", "recipe", "card", "curls", "like", "an", "old", "photograph",
    "shoelaces", "practice", "the", "art", "of", "undoing",
    "the", "door", "mat", "keeps", "a", "museum", "of", "tiny", "stones",
    "a", "whistle", "from", "the", "kettle", "sketches", "a", "skyline",
    "the", "rug", "collects", "constellations", "of", "crumbs",
    "I", "count", "to", "ten", "and", "misplace", "four", "on", "purpose",
    "a", "jacket", "remembers", "a", "ticket", "stub", "like", "a", "pressed", "leaf",
    "the", "moon", "rehearses", "behind", "pale", "afternoon", "clouds",
    "I", "water", "the", "plants", "and", "they", "appear", "politely", "surprised",
    "a", "drawer", "clicks", "shut", "with", "quiet", "conviction"
],
                  "3": [
    "There", "is", "a", "desk", "drawer", "where", "I", "keep", "the", "artifacts", "of", "unfinished", "ideas",
    "ticket", "stubs", "from", "shows", "that", "changed", "nothing", "and", "everything",
    "a", "bent", "paperclip", "that", "once", "saved", "a", "jammed", "key", "on", "a", "tired", "keyboard",
    "a", "tiny", "shell", "from", "a", "beach", "day", "that", "ended", "in", "rain", "and", "laughter",
    "I", "open", "the", "drawer", "sometimes", "just", "to", "remind", "myself", "that", "progress", "is", "a", "collage", "not", "a", "straight", "line",
    "the", "mind", "hoards", "evidence", "that", "efforts", "matter", "even", "when", "outcomes", "wander",
    "I", "find", "a", "postcard", "with", "no", "address", "and", "a", "sketch", "of", "a", "lighthouse",
    "its", "beam", "drawn", "with", "shaky", "confidence",
    "I", "remember", "standing", "in", "wind", "so", "strong", "it", "made", "conversation", "tilt",
    "the", "ocean", "carried", "secrets", "in", "a", "rough", "pocket",
    "foam", "stitched", "edges", "on", "every", "wave",
    "I", "thought", "about", "balance", "and", "how", "a", "foot", "learns", "the", "language", "of", "slippery", "stones",
    "I", "thought", "about", "letters", "I", "never", "sent", "how", "they", "still", "rustle", "in", "some", "quiet", "corner",
    "I", "close", "the", "drawer", "and", "the", "room", "returns", "to", "ordinary", "light",
    "a", "screen", "waits", "with", "its", "steady", "stare",
    "the", "chair", "makes", "a", "small", "complaint", "and", "then", "agrees", "to", "the", "plan",
    "I", "list", "three", "tasks", "and", "then", "add", "a", "fourth", "that", "is", "only", "breathe",
    "coffee", "arrives", "in", "a", "friendly", "cup",
    "a", "spoon", "clinks", "like", "a", "bell", "for", "class",
    "I", "begin", "with", "the", "smallest", "task", "just", "to", "let", "momentum", "introduce", "itself",
    "the", "second", "task", "greets", "me", "with", "a", "minor", "riddle", "and", "I", "answer", "with", "a", "shrug", "and", "a", "guess",
    "somewhere", "outside", "a", "delivery", "truck", "performs", "percussion", "on", "the", "street",
    "a", "laugh", "drifts", "up", "the", "stairwell", "and", "dissolves",
    "I", "underline", "a", "phrase", "and", "it", "suddenly", "grows", "legs",
    "the", "page", "becomes", "a", "small", "field", "where", "thoughts", "graze",
    "I", "herd", "them", "gently", "toward", "the", "fence",
    "a", "notification", "plays", "a", "trumpet", "of", "distraction", "and", "I", "mute", "it", "without", "ceremony",
    "the", "afternoon", "leans", "forward", "as", "if", "curious",
    "time", "stretches", "like", "warm", "taffy", "and", "then", "snaps", "back",
    "I", "check", "the", "drawer", "again", "for", "courage", "and", "find", "a", "stubby", "pencil", "that", "still", "writes", "brave", "lines",
    "I", "keep", "going", "and", "the", "going", "becomes", "its", "own", "reward"
],
                  "4": [
    "In", "the", "kitchen", "a", "pot", "simmers", "with", "the", "steady", "confidence", "of", "practice",
    "onions", "went", "in", "first", "and", "offered", "that", "familiar", "sweetness",
    "then", "garlic", "whispered", "its", "sharp", "hello", "the", "room", "felt", "instantly", "generous",
    "I", "sliced", "carrots", "into", "coins", "and", "listened", "to", "the", "knife", "map", "its", "route",
    "a", "wooden", "spoon", "carries", "the", "history", "of", "dinners", "and", "disagreements",
    "its", "handle", "wears", "a", "smooth", "valley", "where", "patience", "rests",
    "I", "add", "a", "bay", "leaf", "like", "a", "small", "green", "oath",
    "steam", "fogs", "the", "window", "and", "briefly", "paints", "a", "mountain", "range",
    "the", "radio", "murmurs", "a", "quiet", "interview", "about", "someone", "who", "kept", "trying",
    "I", "taste", "and", "add", "salt", "that", "wakes", "the", "broth",
    "pepper", "follows", "like", "a", "friendly", "argument", "the", "pot", "answers", "in", "small", "applause",
    "I", "think", "about", "recipes", "that", "travel", "across", "time", "like", "folded", "letters",
    "grandma", "measurements", "that", "say", "just", "enough", "and", "trust", "your", "hands",
    "the", "kitchen", "timer", "ticks", "like", "a", "crickets", "choir",
    "I", "rinse", "herbs", "and", "the", "sink", "becomes", "a", "tiny", "river",
    "parsley", "confetti", "lands", "on", "the", "cutting", "board",
    "I", "squeeze", "a", "lemon", "and", "the", "air", "gets", "brighter",
    "a", "towel", "hangs", "from", "the", "oven", "door", "like", "a", "flag", "of", "truce",
    "plates", "wait", "with", "a", "calm", "patience", "that", "makes", "me", "smile",
    "the", "table", "invites", "a", "conversation", "it", "has", "hosted", "a", "hundred", "times",
    "chairs", "scuff", "forward", "to", "their", "usual", "marks",
    "I", "ladle", "soup", "into", "bowls", "that", "glow", "with", "a", "humble", "pride",
    "the", "first", "spoonful", "feels", "like", "a", "door", "opening", "in", "winter",
    "warmth", "steps", "in", "with", "a", "generous", "coat",
    "I", "add", "a", "slice", "of", "bread", "that", "gives", "the", "day", "a", "sturdier", "spine",
    "butter", "melts", "into", "small", "golden", "lakes",
    "the", "radio", "song", "changes", "and", "someone", "hums", "without", "noticing",
    "I", "think", "about", "how", "hunger", "is", "not", "only", "a", "stomach", "thing",
    "it", "is", "also", "a", "story", "thing",
    "we", "eat", "to", "remember", "the", "people", "who", "taught", "us", "to", "stir", "and", "to", "wait",
    "we", "eat", "to", "pause", "the", "rush", "and", "build", "a", "small", "circle",
    "the", "pot", "settles", "into", "a", "quiet", "breath",
    "leftovers", "will", "carry", "tomorrow", "on", "an", "easy", "back",
    "the", "sink", "yawns", "water", "hisses", "and", "another", "chapter", "rinses", "clean"
],
                  "5": [
    "At", "night", "the", "neighborhood", "turns", "into", "a", "gentle", "constellation", "of", "windows",
    "each", "one", "a", "soft", "lantern", "holding", "a", "private", "scene",
    "a", "person", "leans", "over", "a", "puzzle", "with", "patient", "concentration",
    "another", "writes", "a", "list", "in", "a", "notebook", "that", "already", "forgives", "crossed", "lines",
    "the", "piano", "on", "the", "second", "floor", "practices", "courage", "one", "note", "at", "a", "time",
    "a", "dog", "patrols", "a", "living", "room", "and", "sighs", "like", "a", "sleepy", "guard",
    "streetlights", "pour", "coins", "of", "amber", "onto", "the", "sidewalk",
    "moths", "spiral", "like", "absent", "minded", "astronomers",
    "a", "bus", "arrives", "and", "exhales", "a", "handful", "of", "travelers", "who", "scatter", "into", "their", "small", "galaxies",
    "somewhere", "a", "kettle", "sings", "and", "then", "remembers", "to", "be", "quiet",
    "curtains", "move", "as", "if", "the", "house", "is", "breathing",
    "I", "walk", "with", "my", "hands", "deep", "in", "my", "pockets", "and", "let", "the", "cool", "air", "polish", "my", "thoughts",
    "a", "bicycle", "glides", "past", "and", "leaves", "a", "silver", "thread", "of", "sound",
    "someone", "waters", "a", "plant", "on", "a", "balcony", "and", "the", "droplets", "fall", "like", "soft", "applause",
    "the", "sky", "is", "stitched", "with", "faint", "stars", "where", "the", "city", "glow", "allows",
    "clouds", "drift", "like", "patient", "ships",
    "I", "pause", "at", "a", "corner", "and", "count", "the", "ways", "light", "touches", "brick",
    "a", "cat", "appears", "from", "under", "a", "parked", "car", "and", "decides", "I", "am", "unimportant",
    "a", "window", "shows", "a", "family", "telling", "a", "story", "with", "lively", "hands",
    "laughter", "escapes", "and", "hops", "across", "the", "street",
    "a", "taxi", "hums", "by", "and", "paints", "yellow", "brushstrokes", "on", "rain", "damp", "asphalt",
    "I", "think", "about", "the", "letters", "I", "should", "write", "and", "the", "calls", "I", "should", "make",
    "the", "night", "collects", "these", "thoughts", "and", "keeps", "them", "safe", "for", "morning",
    "a", "bakery", "in", "the", "distance", "begins", "its", "quiet", "work", "and", "the", "air", "learns", "a", "new", "accent",
    "bread", "prepares", "its", "sunrise",
    "I", "turn", "toward", "home", "and", "the", "key", "waits", "like", "a", "small", "promise",
    "the", "door", "welcomes", "with", "a", "familiar", "weight",
    "shoes", "relax", "by", "the", "mat", "and", "the", "room", "offers", "calm",
    "I", "stand", "in", "the", "soft", "dark", "and", "let", "the", "day", "fold", "itself", "away",
    "the", "quiet", "is", "not", "empty", "it", "is", "full", "of", "gentle", "echoes",
    "and", "the", "steady", "drum", "of", "a", "heart", "that", "keeps", "time", "for", "tomorrow"
]}

